Server:
  port: 8081

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:db_springboot}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:zxcvbnm}